# Generated by Django 4.2.30 on 2026-06-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['user', 'date', 'is_booked'], name='idx_user_date_booked'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['user', 'date', 'start_time', 'end_time'], name='idx_user_date_time'),
        ),
    ]
